pan_blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from blogapp.views import blog, blog_content, comment, jump_bout_me
from blogapp.api import article


urlpatterns = [
    url(r'^$', blog, name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/(?P<cate>[A-Za-z]+)$', blog, name="cate_filter"),
    url(r'^blog/$', blog, name="blog"),
    url(r'^content/(?P<page_num>\d+)$', blog_content, name="content"),
    url(r'^content/(?P<page_num>\d+)/comment$', comment, name="comment"),
    url(r'^api/article', article),
    url("about", jump_bout_me),
]

blogapp/models.py
from django.db import models
from django_markdown.models import MarkdownField
from django.utils import timezone


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = MarkdownField()
    date = models.DateField(null=True, blank=True, default=timezone.now)
    description = models.TextField(blank=True)
    article_type = (
        ('Learning', (
            ('Python', 'python'),
            ('Java', 'java'),
        )
         ),
        ('Life', 'life'),
        ('Other', 'other')
    )
    type = models.CharField(max_length=20, choices=article_type, blank=True)
    lock = models.BooleanField(default=False)
    view_time = models.IntegerField(default=1)
    post_status = models.BooleanField(default=False)
    image_url = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField(null=True, blank=True, max_length=20)
    avatar = models.CharField(null=True, blank=True, max_length=40, default="matt")
    comment = models.TextField()
    auto_date = models.DateTimeField(default=timezone.now)
    is_author = models.BooleanField(default=False)
    belong_to = models.ForeignKey(to=Article, related_name="under_comment", null=True, blank=True)
    parent = models.ForeignKey("self", related_name="reply", blank=True, null=True)
    post_myself = models.BooleanField(default=False)
    email = models.EmailField(blank=True)
    has_children = models.BooleanField(default=False)
    avatar_color = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name

blogapp/forms.py
from django import forms
from django.core.exceptions import ValidationError


def words_validator(comment):
    if len(comment) < 2:
        raise ValidationError("Not enough words, Please ensure your name has at least two words!")


def non_pan(comment):
    if comment == "pan" or comment == "Pan":
        raise ValidationError("Your name can not be mine :( )")


class CommentForm(forms.Form):
    name = forms.CharField(max_length=50, validators=[non_pan])
    comment = forms.CharField(widget=forms.Textarea(), validators=[words_validator])
    # avatar = forms.CharField(widget=forms.HiddenInput(), required=False)
    email = forms.EmailField(required=True)
    parent = forms.IntegerField(widget=forms.HiddenInput(), required=False)

blogapp/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blogapp.forms import CommentForm
from django.utils import timezone

avatar_background_color = (
    ("black", "#4B515E"),
    ("gray", "#ACB8B8"),
    ("yellow", "#F2C42C"),
    ("orange", "#EA9752"),
    ("red", "#E84C3D")
)


# Create your views here.


def blog(request, cate=None):
    check_time_zone()
    context = {}
    article_type = ["Python", "Java", "Life", "Other"]
    if cate is None:
        content = Article.objects.all()
    else:
        if cate.capitalize() in article_type:
            content = Article.objects.filter(type=cate.capitalize())
        else:
            content = Article.objects.all()
    page_robot = Paginator(content.order_by("-date"), 4)
    page_num = request.GET.get("page")
    try:
        article_list = page_robot.page(page_num)
    except EmptyPage:
        article_list = page_robot.page(page_robot.num_pages)
    except PageNotAnInteger:
        article_list = page_robot.page(1)
    context['article_list'] = article_list
    return render(request, 'blog_home.html', context)


def blog_content(request, page_num, error_form=None):
    context = {}
    form = CommentForm
    view_update = Article.objects.get(id=page_num)
    view_update.view_time += 1
    view_update.save()
    context['detail'] = view_update
    comments_for_this_article = Comment.objects.filter(belong_to=view_update)
    comments = comments_for_this_article.filter(parent=None)
    replys = [x for x in comments_for_this_article if x not in comments]
    context['comments'] = comments
    context['replys'] = replys

    if error_form is not None:
        context['form'] = error_form
    else:
        context['form'] = form
    return render(request, 'blog_content.html', context)


def comment(request, page_num):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.cleaned_data["comment"]
        # avatar = form.cleaned_data["avatar"]
        email = form.cleaned_data['email']
        parent_id = form.cleaned_data["parent"]
        # if it is the chilren/parent
        if parent_id:
            parent_model = Comment.objects.get(id=parent_id)
            label_has_chilren(parent_model)
        else:
            parent_model = None
        if request.user.is_authenticated:
            myself = True
            name = "pan"
        else:
            myself = False
            name = form.cleaned_data["name"]
        a = Article.objects.get(id=page_num)
        c = Comment(name=name, comment=comment, belong_to=a, email=email, post_myself=myself, parent=parent_model)
        avatar_color = check_avatar_exist(c)
        c.avatar_color = avatar_color
        c.save()
    else:
        return blog_content(request, page_num, error_form=form)
    return redirect(to="content", page_num=page_num)


def check_avatar_exist(c):
    color = Comment.objects.filter(name=c.name)
    total_number = len(Comment.objects.all())
    if color:
        return color[0].avatar_color
    else:
        return avatar_background_color[(total_number + 1) % 5][1]


def label_has_chilren(parent):
    parent.has_children = True
    parent.save()


def check_time_zone():
    for i in Article.objects.all():
        now = timezone.now().date()
        difference = now - i.date
        stander = timezone.timedelta(days=3)
        if difference <= stander:
            i.post_status = True
            i.save()
        else:
            i.post_status = False
            i.save()


def jump_bout_me(request):
    return render(request, "about_me.html")

templates/about_me.html
<!DOCTYPE html>

{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    <link rel="apple-touch-icon">
    <link rel="icon" href="{% static "img/logo.png" %}">
    <title>About me</title>
    <link rel="stylesheet" href={% static "css/semantic.css" %}>
    <link rel="stylesheet" href="{% static "css/git.css" %}">
<style>
body {
    margin-top:30px;
    margin-bottom:30px;
}

table tr td {
    border: none;
    padding:0;
}
</style>
</head>
<body>
<h2>关于我</h2>


<table>
    <tr>
        <td>
            <p>
                HI，我的名字是<b>袁登攀</b>(看清楚，我很讨厌些眼神不好把我叫做<b>袁攀登</b>的家伙哦)。我来自陕西西安，一座富有文化内涵的城市，人杰地灵，古色古香。我家里共有4名家庭成员，我的父亲是一家地产公司的项目经理，母亲是全职家庭主妇（<i>从我出生开始</i>），有一个哥哥，我和他的关系很好。我现在在罗格斯大学就读信息与计算机专业（之前在西安交通利物浦大学就读），喜欢体验新鲜的事物。
            </p>
        </td>
        <td>
        <img src="http://otr4re8c8.bkt.clouddn.com/self_photo.png" alt=""
     style="max-width:100%;max-height:100%;">
        </td>
    </tr>
</table>

<h2>爱好</h2>

<p>我的爱好广泛，虽然不能都达到出神入化的地步，但大多数的爱好都是涉猎后感兴趣的。</p>


<ul>
    <li>摄影，入门级ps水平，索狗。</li>
    <li>编程，网站搭建与人工智能，三流程序员水平。</li>
    <li>健身，还在努力减体脂，希望BMI下降到20%。</li>
    <li>读书，有一个Kindle，长途旅行的最佳选择。</li>
    <li>Fine art, 不同艺术家的表达手法，穆夏，提香，丢勒...</li>
    <li>各式各样的威化饼，最钟爱干脆不油腻，不是很甜的品类。</li>
    <li>RTS，偶尔会玩玩war craft,红警，AOE...</li>
    <li>流行歌，无特别喜爱歌手，品味大众化，billborad前茅的歌曲基本都喜欢。</li>
    <li>学习，任何感兴趣的知识技能。</li>
    <li>衣服，鞋子， 虽然没钱买奢侈潮牌，但是很喜欢通过不同颜色的组合搭配出自己认为很好看的套装。</li>
    <li>美食，和好友每周必有一次饭局，品尝各种独特的小馆。</li>
    <li>荒岛求生的纪录片或者电影，远离现代文明。</li>
    <li>科技，玲琅满目的电子设备，购买欲不强但会花时间去专卖店体验。</li>
</ul>


<h2>愿望</h2>

<ul>
    <li>一次格陵兰之旅，出海看冰山，观鲸，带上相机拍摄北极光。</li>
    <li>南美玻利维亚镜湖拍组照片，乌尤尼盐沼看夕阳。</li>
    <li>带父母来次欧洲深度游，花费自己的钱。</li>
    <li>学一门西方乐器，希望靠乐器认识一些朋友。</li>
    <li>一辆自己的跑车。</li>
</ul>
</body>
</html>

templates/blog_content.html
<!DOCTYPE html>
{% load static %}
{% load custom_markdown %}
{% load avatar_filter %}
<html>
<head>
    <meta charset="utf-8">
    <title>{{ detail.title }} - pan blog</title>
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon">
    <link rel="apple-touch-icon">
    <link rel="stylesheet" href="{% static "css/blog_content.css" %}">
    <link rel="stylesheet" href="{% static "css/semantic.css" %}">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kurale" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/highlight.css" %}">
    <link rel="stylesheet" href="{% static "css/git.css" %}">
    <link rel="icon" href="{% static "img/logo.png" %}">
    <link rel="stylesheet" href="{% static "css/avatar.css" %}">
    <link rel="stylesheet" href="{% static "css/colorbox.css" %}">
    <script rel="script" src={% static "js/jquery.js" %}></script>
    <script rel="script" src={% static "js/semantic.js" %}></script>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {inlineMath: [['$', '$']]}
        });
    </script>
    <script src={% static "js/photoswipe/photoswipe-ui-default.min.js" %}></script>
    <script src={% static "js/photoswipe/photoswipe.min.js" %}></script>
    <script src="{% static "js/jquery.colorbox.js" %}"></script>
    <script src="{% static "js/jquery.photoset-grid.js" %}"></script>
    <script type="text/javascript"
            src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
</head>

<body>


{# old blog does not have backgound pic #}
<div id="background-picture"
     style="background-image: url({{ detail.image_url }});">
    <i class="home very big link icon" id="nav-home" onClick=" location.href='{% url "blog" %}'"> </i>
    <h1 class="background_script" style="bottom: 5%;left:10%;">Just Simple</h1>
</div>

<h6 id="time">
    {{ detail.date }}
</h6>

<h1 id="title" style="margin-bottom:1.3em;">
    {{ detail.title }}
    <p id="subtitle">
        {{ detail.description }}
    </p>
</h1>

{{ detail.content | custom_markdown }}


{#<div style="float: right;height:25px">#}
{#    <a href="{% url "cate_filter" detail.type %}" style="display: block">#}
{#        # {{ detail.type }}#}
{#    </a>#}
{#</div>#}


<div id="last-part">
    <div id="comment-block">

        <div id="ui comment">
            <div class="ui threaded comments">
                <h3 class="ui dividing header">Comments</h3>
                {# have no comments #}
                {% if comments.count == 0 %}
                    <span> No one has been commented, give a comment.</span>

                {% else %}

                    {% for comment in comments %}
                        <div class="ui comment">
                            <a class="avatar">
                                {# the photo of my self #}
                                {% if comment.post_myself %}
                                    <img src="{% static "img/pan.jpg" %}" style="width:35px; height:35px;"
                                         alt="">
                                {% else %}
                                    <div style="background-color:{{ comment.avatar_color }}"
                                         class="avatar-block">{{ comment.name.0 }}</div>
                                    {#                                <img src="{% static "comment-avatar.jpg" %}" style="width:35px; height:35px;"#}
                                    {#                                     alt="">#}
                                {% endif %}
                            </a>

                            <div class="content">
                                {% if comment.post_myself %}
                                    <a class="author">{{ comment.name }}</a>
                                {% else %}
                                    <a class="author">{{ comment.name | cut_avatar_name }}</a>
                                {% endif %}
                                <div class="metadata" id="date">
                                    <span class="date">{{ comment.auto_date }}</span>
                                </div>

                                <div class="text" style="padding:0;">
                                    {{ comment.comment | custom_markdown }}
                                </div>

                                <div class="actions">
                                    <a class="reply" onclick="switch_display('write-{{ comment.id }}')"
                                       style="color: #a0d6b4;">Reply</a>
                                </div>

                                {# your reply #}
                                <div id="write-{{ comment.id }}" style="display: none; padding:30px;">
                                    <div class="ui dividing header">
                                        Your Reply
                                    </div>

                                    <form class="ui error tiny form" method="post"
                                          action="{% url "comment" detail.id %}"
                                          style="">
                                        {#   wrong form     #}
                                        {% if form.errors %}
                                            <div class="ui error message">
                                                {{ form.errors }}
                                            </div>
                                            {% for hidden in form.hidden_fields %}
                                                <div class="field">
                                                    <input id="avatar_input" type="hidden" name="avatar">
                                                </div>
                                            {% endfor %}
                                            {% for field in form.visible_fields %}
                                                <div class="{{ field.errors|yesno:"error, " }} field">
                                                    {{ field.label }}
                                                    {{ field }}
                                                </div>
                                            {% endfor %}
                                        {% else %}
                                            {% for field in form.visible_fields %}
                                                <div class="field">
                                                    {{ field.label }}
                                                    {{ field }}
                                                </div>
                                            {% endfor %}
                                            {% for hidden in form.hidden_fields %}
                                                <input type="hidden" name="parent" id="id_parent"
                                                       value="{{ comment.id }}">
                                            {% endfor %}
                                        {% endif %}
                                        {% csrf_token %}
                                        <button class="ui positive right labeled icon button" type="submit" id="sub-bun"
                                                id="window_locate">
                                            Submit it!
                                            <i class="checkmark icon"></i>
                                        </button>
                                    </form>
                                </div>


                                {# if it has reply  #}
                                {% if comment.has_children %}
                                    {# filter the same id parent reply #}
                                    <div class="comments" style="margin-top:10px; padding-top:20px;">
                                        {% for reply in replys %}
                                            {% if reply.parent == comment %}
                                                <div class="comment" style="margin-bottom:35px">
                                                    <a class="avatar">
                                                        {# the photo of my self #}
                                                        {% if reply.post_myself %}
                                                            <img src="{% static "img/pan.jpg" %}"
                                                                 style="width:35px; height:35px;"
                                                                 alt="">
                                                        {% else %}
                                                            <div style="background-color:{{ reply.avatar_color }}"
                                                                 class="avatar-block">{{ reply.name.0 }}</div>
                                                        {% endif %}
                                                    </a>
                                                    <div class="content">
                                                        {% if reply.post_myself %}
                                                            <a class="author">{{ reply.name }}</a>
                                                        {% else %}
                                                            <a class="author">{{ reply.name | cut_avatar_name }}</a>
                                                        {% endif %}

                                                        <div class="metadata">
                                                            <span class="date">{{ reply.auto_date }}</span>
                                                        </div>
                                                        <div class="text">{{ reply.comment }}</div>
                                                    </div>
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        {# endfor the comment #}
                    {% endfor %}

                    {# endif the exclude conunt part #}
                {% endif %}

                <button class="ui right labeled icon button" onclick="switch_display('write-comment')"
                        style="margin-top:30px;">
                    Write
                    <i class="write icon"></i>
                </button>

            </div>
        </div>

        {# comment form #}
        <div id="write-comment" style="display: none; padding:30px;">
            <h3 class="ui dividing header">
                Your comment
            </h3>

            <form class="ui error tiny form" method="post" action="{% url "comment" detail.id %}" style="">
                {#   wrong form     #}
                {% if form.errors %}
                    <div class="ui error message">
                        {{ form.errors }}
                    </div>
                    {% for hidden in form.hidden_fields %}
                        <div class="field">
                            <input id="avatar_input" type="hidden" name="avatar">
                        </div>
                    {% endfor %}
                    {% for field in form.visible_fields %}
                        <div class="{{ field.errors|yesno:"error, " }} field">
                            {{ field.label }}
                            {{ field }}
                        </div>
                    {% endfor %}
                {% else %}
                    {% for field in form.visible_fields %}
                        <div class="field">
                            {{ field.label }}
                            {{ field }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% csrf_token %}
                <button class="ui positive right labeled icon button" type="submit" id="sub-bun" id="window_locate">
                    Submit it!
                    <i class="checkmark icon"></i>
                </button>
            </form>
        </div>
    </div>

</div>

<script>
    $('.photoset-grid-lightbox').photosetGrid({
        highresLinks: true,
        rel: 'withhearts-gallery',
        gutter: '4px',

        onComplete: function () {
            $('.photoset-grid-lightbox').attr('style', '');
            $('.photoset-grid-lightbox a').colorbox({
                photo: true,
                scalePhotos: true,
                maxHeight: '90%',
                maxWidth: '90%'
            });
        }
    });
</script>

<script>
    function switch_display(id) {
        comment = document.getElementById(id);
        if (comment.style.display == "none") {
            comment.style.display = "block";
            //if it is the write button
            if (id == "write-comment") {
                window.scrollTo(0, document.body.scrollHeight);
            }
        } else {
            comment.style.display = "none";
        }
    }
</script>
</body>
</html>

templates/blog_home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>pan blog</title>
    <link rel="stylesheet" href={% static "css/semantic.css" %}>
    <link rel="stylesheet" href={% static "css/pan_blog.css" %}>
    <link href="https://fonts.googleapis.com/css?family=Roboto|Timmana" rel="stylesheet">
    <link rel="icon" href="{% static "img/logo.png" %}">
    <script rel="script" src={% static "js/jquery.js" %}></script>
    <script rel="script" src={% static "js/jquery.waypoints.min.js" %}></script>
    <script rel="script" src="{% static "js/infinite.min.js" %}"></script>
</head>
<body>

<div class="head">
    <div class="inner" style="max-width: 1100px;">
        <a class="head-logo" href="{% url "home" %}">Just Simple</a>
        <nav class="head-nav-color" style="float: right;">
            <a href="{% static "finished_aviator/index.html" %}" style="color:cornflowerblue;"># About</a>
        </nav>
    </div>
</div>

<div class="info">
    <div class="inner">
        <a class="info_logo" href="{% url "home" %}">
            <img src="{% static "img/logo.png" %}">
        </a>
        <div class="info_main">
            <h1 class="info_title">
                <a style="color:black;" href="{% url "home" %}">
                    pan blog
                </a>
            </h1>
            <h2 class="info_subtitle">
                一个人行走的范围，便是他的世界.
            </h2>
        </div>
        <div class="info_social">
            <a href="https://github.com/PanPython123">
                <i class="ui icon github"></i>
            </a>
            <a href="https://twitter.com/Cookie_Yuan_">
                <i class="ui icon twitter"></i>
            </a>
        </div>
    </div>
</div>


<div class="main">

    <div class="infinite-container">
        {% for article in article_list %}
            <div class="infinite-item">
                <div class="inner">
                    <div class="item Article Cover" lang="zh">
                        <a class="item-cover" href="{% url 'content' article.id %}">
                            {% if article.image_url %}
                                <div class="item-cover-image">
                                    <div class="cover-image"
                                         style="background-image:url({{ article.image_url }}); height: 100%; width: 100%"></div>
                                </div>
                                <div class="item-cover-inner">
                                <time class="date">{{ article.date }}</time>
                                <h3 class="inner-title">{{ article.title }}</h3>
                                <h4 class="inner-description">{{ article.description }}</h4>
                                </div>
                            {% else %}
                                <div class="item-non-cover-inner">
                                    <time class="date">{{ article.date }}</time>
                                    <h3 class="inner-title">{{ article.title }}</h3>
                                    <h4 class="inner-description">{{ article.description }}</h4>
                                </div>
                            {% endif %}
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}

    {% if article_list.has_next %}
        <a class="infinite-more-link" href="?page={{ article_list.next_page_number }}"></a>
    {% endif %}

    <div class="loading" style="display: none;">
        Loading...
    </div>
</div>
</div>

<script>
    {#    var content = $(".infinite-container")[0];#}
    var infinate = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        onBeforePageLoad: function () {
            $('.loading').show();
        },
        onAfterPageLoad: function () {
            $('.loading').hide();
        }
    });

    {#    var inner_images = $(".a")#}

</script>

</body>
</html>

templates/fail_authorize.html
{% extends "blog_content.html" %}
{% block ten-content %} <h1>You are not allowed</h1>{% endblock %}

templates/new.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="css/semantic.css">
    <link rel="stylesheet" href="css/animate.css">
    <script type="text/javascript" src="js/jquery.js">

    </script>
    <script type="text/javascript" src="css/semantic.js">

    </script>
</head>
<body>

    <div class="ui sidebar inverte top five item menu">

        <div class="item">
            <div class="ui dropdown item" id="hideden-dropdown">
                类目
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="#" class="item">Electronics</a>
                    <a href="#" class="item">Electronics</a>
                    <a href="#" class="item">Electronics</a>
                </div>
            </div>
        </div>

        <a class="item">
            2
        </a>
        <a class="item">
            3
        </a>
        <a href="#" class="item">4</a>
        <a href="#" class="item">5</a>
    </div>

    <div class="pusher">
        <div class="ui button" id="menu">
            menu
        </div>

        <button type="button" name="button" class="ui red button" id="tran-bun">TestDimmer</button>

        <div class="ui segment" id="test-tran" style="margin:10%;">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
            magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
            laborum.
        </div>
        =
    </div>


    <script>
        $('#menu').click(function () {
            $('.sidebar')
                    .sidebar('setting', 'transition', 'overlay')
                    .sidebar('toggle')
            ;
        }),
                $(".ui.inline.dropdown").dropdown('show'),
                $('#hideden-dropdown').dropdown('show'),
                $('#test-tran')
                        .transition('jiggle')
        ;
    </script>

</body>
</html>